# # version: "3"
# # services:
# #   front-app:
# #     image: front-app
# #     ports: 
# #       - "3000:3000"
# #     networks:
# #       - code-chal-app
# #     depends_on:
# #       - back-app
# #   back-app:
# #     image: back-app
# #     ports:
# #       - "8080:8080"
# #     networks:
# #       - code-chal-app
# # networks:
# #   code-chal-app:
# #     driver: bridge
# # volumes:
# #   backup-data: 
# #     driver: local


# version: "3"
# services:
#   back-app:
#     image: back-app
#     ports:
#       - "8080:8080"
      
#     networks:
#       - code-chal-app
#   front-app:
#     image: front-app
#     ports: 
#       - "3000:3000"

#     networks:
#       - code-chal-app
#     depends_on:
#       - back-app
# networks:
#   code-chal-app:
#     driver: bridge
# volumes:
#   backup-data:
#     driver: local


version: '3'
services:
  front:
    container_name: frontend-container
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - code-chal-app
    depends_on:
      - back
  back:
    container_name: backend-container
    expose:
      - "8080"
    build: .
    ports:
      - "8080:8080" 
    networks:
      - code-chal-app
volumes:
  backup-data:
networks:
  code-chal-app:
    driver: bridge
  # networks:
  #   driver: bridge
# volumes:
#   backup-data: 
#     driver: local